### ISSUE TITLE
Memory Short

### ISSUE THREAD

**Issue by Kalidomra** [robinhedwards/UltimateCart#4]
I have tried to build this twice. Each time there seems to be a dead short to the memory after programming. Everything is fine, I program the chip and the memory chips gets too hot to touch. What am I doing wrong?

**Comment by pazuzu72** [comment]
> I have tried to build this twice. Each time there seems to be a dead short to the memory after programming. Everything is fine, I program the chip and the memory chips gets too hot to touch. What am I doing wrong?

Can you post a photo of pcb populated?

**Comment by Kalidomra** [comment]
Sure, here it is.
![IMG_20201220_162106563](https://user-images.githubusercontent.com/40541205/102726926-a0550a00-42df-11eb-816c-34009b5013e4.jpg)

**Comment by pazuzu72** [comment]
The photo is not very clear. Are you sure there is no solder bridge?

**Comment by Kalidomra** [comment]
Here is what I have done:

1st attempt:
- Soldered all of the parts, inspected for solder bridges. Powered the board, no issues. Minimal power draw.
- Programmed the Altera.
- After programming, upon power up the board was drawing too much power and memory was hot to the touch.
- Powered down.
- Removed the memory, installed on a blank board.
- Powered the new blank board, memory was still drawing too much power and getting hot.
- Reinspected the original board via microscope, no solder bridges. 
- Ordered new memory chip, installed, same result. 
- Gave up

2nd attempt:
- Ordered all new parts.
- Install everything except U1-4, SD card socket and switch.
- Triple checked every connection. 
- Same result as first attempt.

**Comment by pazuzu72** [comment]
I have no idea !! I've done more than 130, this has never happened to me. I program them directly powered by an atari computer, not via the external 2 pin header. Nothing else comes to mind.

**Comment by jhusak** [comment]
I think the issue may be in unstable inputs when no level shifters installed. I would solder them in and then test.
This is non-standard behavior when mounting only some parts, not all, as other people do, leading almost always to problems.

**Comment by Kalidomra** [comment]
In my first attempt I had all of the components installed prior to programming.  There may be an issue with the gerber files I generated. Would it be possible to post the gerbers for the successful builds?

**Comment by pazuzu72** [comment]
[Ulimate_2020-12-31.zip](https://github.com/robinhedwards/UltimateCart/files/5757515/Ulimate_2020-12-31.zip)
Sure!

**Comment by pazuzu72** [comment]
[Ultimate_Cart_gerber.zip](https://github.com/robinhedwards/UltimateCart/files/5757521/Ultimate_Cart_gerber.zip)
Sure!

**Comment by Kalidomra** [comment]
Is it possible that powering the board without being hooked to the logic and pull up or pull downs of the Atari is causing the Altera to get in a state that drives the WE High and also tries to drive the Data pins?

**Comment by mulcmu** [comment]
I built 3 and programmed them using the external +5V power input headers without being installed in an Atari.

**Comment by pazuzu72** [comment]
> Is it possible that powering the board without being hooked to the logic and pull up or pull downs of the Atari is causing the Altera to get in a state that drives the WE High and also tries to drive the Data pins?

I don't think that's the problem!

**Comment by Kalidomra** [comment]
I have been doing a little troubleshooting today. I  setup the scope on the 5v rail and noticed a 13v spike for 6ms when switching on the bench power supply. Would that be enough to fry the sram? I have also checked the entire board, there are no shorts, it is all connected correctly.

**Comment by jhusak** [comment]
Well, I would throw away such a "stabilized" power supply. Yes, it would kill your chips. 6 ms is a long time.

**Comment by Kalidomra** [comment]
Yup, cheap POS. New one on order. I will also get some new  SRAM and try again. I'm sure that was the issue. Thanks for all the help.

**Comment by pazuzu72** [comment]
You can power it inserted in atari cartridge port for programming!!! I always do in that way.

**Comment by Kalidomra** [comment]
New memory installed, programmed with power from Atari. Everything works as expected. Thanks.
