### ISSUE TITLE
FPGA

### ISSUE THREAD

**Issue by Icelvlan88** [robinhedwards/UltimateCart#6]
Hello,

Is it possible to use this on another FPGA? These are very difficult to find right now

**Comment by Pinjontall94** [comment]
Mouser in fact lists them as [obsolete in terms of lifecycle](https://www.mouser.com/ProductDetail/Intel-Altera/10M08SAE144C8GES?qs=1Tf3zEaA732qEM1Omr%252Bn4w%3D%3D) so a replacement is definitely needed! If these chips aren't used up already (and not just in shortage), presumably they will be in the near-ish future

**Comment by robinhedwards** [comment]
You've linked to the 10M08SAE144C8G/ES which was the engineering sample available when the cart was created.
The standard production version (10M08SAE144C8G) is **not obsolete**, though I gather its impossible to find at the moment.
[Mouser](https://www.mouser.co.uk/ProductDetail/Intel-Altera/10M08SAE144C8G?qs=RaMzjY%252B%252BwSmf%2FTEPGlobiw%3D%3D) is showing stock coming later in 2023.
